#!/bin/bash

set -e
shopt -s globstar

usage () {
	echo "Usage:"
	echo "    filepick [--[no-]accept-query]"
	echo "             [--exclude=<pattern> ...]"
	echo "             [--geometry=<geometry>]"
	echo "             [--[no-]hidden]"
	echo "             [--home-query=<query>]"
	echo "             [--initial-query=<query>]"
	echo "             [--loop|--dir-opener=<opener>]"
	echo "             [--mode=<mode>]"
	echo "             [--prompt=<prompt>]"
	echo "             [--target=<file>]"
	echo "             [--title=<title>]"
	echo "             [<root>]"
}

fail () {
	>&2 echo "$1"
	>&2 usage
	exit 1
}

open_with_editor () {
	local editor="$1"
	local item="$2"

	# If attached to a terminal, just edit the item from it and quit.
	[ -t 0 ] && exec $editor -- "$item"

	# Otherwise, spawn a new terminal and then edit the item.
	local term=${FILEPICK_TERM:-${TERMCMD:-xterm}}
	EDITOR="$editor" setsid $term -e $editor -- "$item" &
	exit 0
}

editor=${FILEPICK_EDITOR:-${VISUAL:-${EDITOR:-vi}}}
excludes=()
hidden_arg=--hidden
geometry=
while [ "$#" -gt 0 ]; do
	case $1 in
		--accept-query)
			accept_query_arg=--accept-query
			;;
		--no-accept-query)
			accept_query_arg=
			;;

		--dir-opener=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--dir-opener requires argument"
			[ -n "$dir_opener" ] && fail "--dir-opener set multiple times: $dir_opener, $arg"
			dir_opener="$arg"
			;;
		--dir-opener)
			shift
			[ -z "$1" ] && fail "--dir-opener requires argument"
			[ -n "$dir_opener" ] && fail "--dir-opener set multiple times: $dir_opener, $1"
			dir_opener="$1"
			;;

		-E=*|--exclude=*)
			exclude="${1#*=}"
			[ -z "$exclude" ] && fail "--exclude requires argument"
			excludes+=("${exclude}")
			;;
		-E|--exclude)
			shift
			exclude="$1"
			[ -z "$exclude" ] && fail "--exclude requires argument"
			excludes+=("${exclude}")
			;;

		-h|--help)
			echo "filepick: select a file or directory using fd and pickout and open it using xdg-open or your text editor"
			echo
			usage
			echo
			echo "Options:"
			echo "    --[no-]accept-query"
			echo "                     sets or resets pickout option --accept-query."
			echo "    --dir-opener=<opener>"
			echo "                     program used to open directories (default: xdg-open)."
			echo "    --exclude=<pattern>"
			echo "                     fd(1) option --exclude (multiple can be given)."
			echo "    --geometry=<geometry>"
			echo "                     pickout option --qwindowgeometry."
			echo "    --[no-]-hidden   sets or resets fd(1) option --hidden. Default is --hidden."
			echo "    --home-query=<query>"
			echo "                     pickout option --home-query."
			echo "    --initial-query=<query>"
			echo "                     pickout option --initial-query."
			echo "    --loop           directories start a new session, loop until a non-directory is selected/entered."
			echo "    --mode=<mode>    \"copy\", \"open\" or \"echo\", see below (defaults to \"open\")."
			echo "    --prompt=<prompt>"
			echo "                     pickout option --prompt, uses mode by default."
			echo "    --target=<file>  skip selection menu and use this file as the result."
			echo "    --title=<title>  pickout option --qwindowtitle (a default one is used if not given)."
			echo "    <root>           the root directory to select files from (defaults to \$HOME)."
			echo
			echo "Modes:"
			echo "    copy             copy selection to Wayland clipboard."
			echo "    open             open selection using xdg-open or your editor."
			echo "    echo             echoes selection to standard output."
			echo
			echo "Environment variables:"
			echo "    FILEPICK_EDITOR, VISUAL, EDITOR"
			echo "                     the editor to use to open new files."
			echo "    FILEPICK_TERM, TERMCMD"
			echo "                     the terminal in which to use the editor (defaults to xterm)."
			exit 0
			;;

		--geometry=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--geometry requires argument"
			[ -n "$geometry" ] && fail "--geometry set multiple times: $geometry, $arg"
			geometry="$arg"
			;;
		--geometry)
			shift
			[ -z "$1" ] && fail "--geometry requires argument"
			[ -n "$geometry" ] && fail "--geometry set multiple times: $geometry, $1"
			geometry="$1"
			;;

		--hidden)
			hidden_arg=--hidden
			;;
		--no-hidden)
			hidden_arg=
			;;

		# Contrary to other options, --home-query and --initial-query accept an
		# empty argument. They can be set to an empty string and reset to a
		# non-empty string, but the opposite is not allowed.
		--home-query=*)
			arg="${1#*=}"
			[ -n "$home_query" ] && fail "--home-query set multiple times: $home_query, $arg"
			home_query="$arg"
			;;
		--home-query)
			shift
			[ -n "$home_query" ] && fail "--home-query set multiple times: $home_query, $1"
			home_query="$1"
			;;
		--initial-query=*)
			arg="${1#*=}"
			[ -n "$initial_query" ] && fail "--initial-query set multiple times: $initial_query, $arg"
			initial_query="$arg"
			;;
		--initial-query)
			shift
			[ -n "$initial_query" ] && fail "--initial-query set multiple times: $initial_query, $1"
			initial_query="$1"
			;;

		--loop)
			loop=true
			;;

		--mode=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--mode requires argument"
			[ -n "$mode" ] && fail "--mode set multiple times: $mode, $arg"
			mode="$arg"
			;;
		--mode)
			shift
			[ -z "$1" ] && fail "--mode requires argument"
			[ -n "$mode" ] && fail "--mode set multiple times: $mode, $1"
			mode="$1"
			;;

		--prompt=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--prompt requires argument"
			[ -n "$prompt" ] && fail "--prompt set multiple times: $prompt, $arg"
			prompt="$arg"
			;;
		--prompt)
			shift
			[ -z "$1" ] && fail "--prompt requires argument"
			[ -n "$prompt" ] && fail "--prompt set multiple times: $prompt, $1"
			prompt="$1"
			;;

		--target=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--target requires argument"
			[ -n "$target" ] && fail "--target set multiple times: $target, $arg"
			target="$arg"
			;;
		--target)
			shift
			[ -z "$1" ] && fail "--target requires argument"
			[ -n "$target" ] && fail "--target set multiple times: $target, $1"
			target="$1"
			;;

		--title=*)
			arg="${1#*=}"
			[ -z "$arg" ] && fail "--title requires argument"
			[ -n "$title" ] && fail "--title set multiple times: $title, $arg"
			title="$arg"
			;;
		--title)
			shift
			[ -z "$1" ] && fail "--title requires argument"
			[ -n "$title" ] && fail "--title set multiple times: $title, $1"
			title="$1"
			;;

		*)
			[ -n "$root" ] && fail "root set multiple times: $root, $1"
			root="$1"
			;;
	esac

	shift
done

[ -z "$mode" ] && mode="open"

if [ "$mode" = "copy" ]; then
	title_suffix=" to copy filename"
elif [ "$mode" = "open" ]; then
	title_suffix=" to open or edit"
elif [ "$mode" = "echo" ]; then
	title_suffix=" to echo"
else
	fail "invalid mode $mode"
fi

if [ -n "$loop" ] && [ -n "$dir_opener" ]; then
	fail "use one of --loop or --dir-opener, not both"
fi

dir_opener=${dir_opener:-xdg-open}
root=${root:-$HOME}
title=${title:-"Select file${title_suffix}…"}
geometry_arg=
[ -n "$geometry" ] && geometry_arg="--qwindowgeometry $geometry"

fd_options=". --type file --follow $hidden_arg --no-ignore-vcs"

# $initial_query is taken as a filesystem path. Make sure its directory is not excluded.
[ -f "${initial_query}" ] && initial_query_dir=$(dirname "${initial_query}")
[ -d "${initial_query}" ] && initial_query_dir="${initial_query}"
fd_exclude_args=()
if [ -n "${initial_query_dir}" ]; then
	for glob in "${excludes[@]}"; do
		case "${initial_query_dir}" in
			${glob})
				continue
				;;
			*)
				fd_exclude_args+=("--exclude" "${glob}")
				;;
		esac
	done
else
	for glob in "${excludes[@]}"; do
		fd_exclude_args+=("--exclude" "${glob}")
	done
fi

while true; do
	root="${root%/}"
	cd "$root"
	if [ -z "$target" ]; then
		item=$(
		  fd $fd_options "${fd_exclude_args[@]}" | \
			pickout \
				$accept_query_arg \
				$geometry_arg \
				--history-key "file://$PWD" \
				--home-query "$home_query" \
				--initial-query "$initial_query" \
				--qwindowtitle "$title" \
				--word-delimiters '._-' \
				--big-word-delimiters '/' \
				--prompt "${prompt:-$mode}"
		) || exit 1

		# Treat item as a file/dir with respect to root unless it starts with /
		case "$item" in /*) ;; *) false;; esac || item="$root/$item"
	else
		item="$target"
	fi

	if ([ -d "$item" ] && [ -n "$loop" ]); then
		# In loop mode, always deliver a file, never a directory. Change root
		# and restart.
		root="$item"
		# Also, the initial query likely makes no sense anymore. Unset it.
		initial_query=""
		continue
	fi

	[ "$mode" = "echo" ] && echo "$item" && exit 0

	if [ "$mode" = "copy" ]; then
		# Assume Wayland and copy item to the clipboard.
		wl-copy "$item"
		# Show a notification popup in the user's desktop.
		command -v notify-send &>/dev/null && notify-send -u normal "filepick" "Copied $item"
		exit 0
	fi

	# mode is "open"

	# If this is a directory, open it and quit.
	[ -d "$item" ] && exec $dir_opener "$item"

	# If the item is an existing file, open it and quit.
	if [ -f "$item" ]; then
		# Use user's editor if the file looks like text or is empty.
		if file -Lbrk "$item" | grep -q -P "(Unicode|ASCII) text|empty"; then
			open_with_editor "$editor" "$item"
		fi

		# Otherwise, delegate it to xdg-open.
		EDITOR="$editor" exec xdg-open "$item"
	fi

	# Not a file or a directory. Attempt to edit it (the user's editor will
	# likely create a new file, possibly creating any necessary intermediary
	# directories).
	open_with_editor "$editor" "$item"
done
