#!/bin/bash

set -e

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(cd "$(dirname "$script_path" )" && pwd)"
venv_path="$script_dir/venv"
source "$venv_path/bin/activate"
exec python "$script_dir/main.py" "$@"
