#!/usr/bin/env python3
"""Pickout.

Usage:
    pickout [--accept-input]
            [--app-name=<name>]
            [--completion-sep=<sep>]
            [--debug]
            [--history-key=<key>]
            [--input=<input>]
            [--json-output]
            [--limit=<limit>]
            [--loop]
            [--no-center]
            [--title=<title>]
            [--word-delimiters=<delimiters>]

Options:
    --accept-input
        Allow any text typed in the search input to be accepted through
        Ctrl-Enter.

    --app-name <name>
        [default: pickout]

        In X11 this will be added to the WM_CLASS property of the main window.

    --completion-sep <sep>
        Separator used for completion.  Without this, completion works by
        completing longest common match.  This can be used to complete only
        directories in a list of files, for instance: use '/' (or OS path
        separator) for this.

    --debug
        Print additional information to STDERR.

    --history-key <key>
        A key which must be unique to store/retrieve history.  Any string can
        be used.  History is enabled only if this option is provided and is not
        empty.

        For instance, if listing all files under a specific directory, use that
        directory as the key.  Next time this program is used for this
        directory, it'll remember the previous input, allowing the user to
        reuse it.

    -i <input>, --input <input>
        Use <input> as a initial value.

    --json-output
        Return the selection as a JSON array.

    -l <limit>, --limit <limit>
        Limit output up to <limit> results.  Use a negative number to not limit
        output.

    --loop
        Don't quit until SIGTERM is received or the menu window is closed, and
        wait new items on STDIN after printing a selection to STDOUT, in a
        loop.

        Items are read from STDIN until a blank line is read (which is
        ignored).  A selection is written to STDOUT, followed by a blank line.
        If no selection is made, a single blank line is printed.

    --no-center
        Do not move window to the center of the screen.

    --title <title>
        Set the window title to <title>.

    --word-delimiters <delimiters>
        Delimiters used for words.

    -h, --help
        Show this.

Key bindings:

    Enter
        Accept the selected item, that is, print it to STDOUT and exit.

    Ctrl+Enter
        Accept the input, that is, print it to STDOUT and exit.

    Esc or Ctrl+Space
        Quit, without printing anything.

    Tab
        Complete.

    CTRL+J
        Select next entry.

    CTRL+K
        Select previous entry.

    Ctrl+N
        Get next history entry and use it as the input.

    Ctrl+P
        Get previous history entry and use it as the input.

    Ctrl+Y
        Copy selected entry to the input box.
"""

from app import run, read_io
from docopt import docopt

import json
import sys


def main(args):
    limit = args['--limit']
    limit = int(limit) if limit and int(limit) >= 0 else None
    entries = read_io(sys.stdin)

    return run(
        entries,
        logger=sys.stderr if args['--debug'] else None,
        loop=args['--loop'],
        app_name=args['--app-name'],
        input=args['--input'],
        limit=limit,
        center=not args['--no-center'],
        sep=args['--completion-sep'],
        delimiters=list((args['--word-delimiters'] or '')),
        history_key=args['--history-key'],
        accept_input=args['--accept-input'],
        json_output=args['--json-output'],
        title=args['--title']
    )


if __name__ == '__main__':
    sys.exit(main(docopt(__doc__)))
